// Generated by CoffeeScript 1.3.3
(function() {
  var Manju, MomijiManju, manju1, momijiManju1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Manju = (function() {

    Manju.prototype.shape = 'ball';

    function Manju() {
      alert('まんじゅう作成完了');
    }

    Manju.prototype.sayShape = function() {
      alert(this.shape);
      return this;
    };

    return Manju;

  })();

  MomijiManju = (function(_super) {

    __extends(MomijiManju, _super);

    MomijiManju.prototype.shape = 'momiji';

    function MomijiManju() {
      MomijiManju.__super__.constructor.apply(this, arguments);
      alert('もみじまんじゅう！');
    }

    return MomijiManju;

  })(Manju);

  manju1 = new Manju;

  manju1.sayShape();

  momijiManju1 = new MomijiManju;

  momijiManju1.sayShape();

}).call(this);
