// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $('.tabSet').each(function() {
      var anchors, lastAnchor, lastPanel, panelDivs, topDiv;
      topDiv = $(this);
      anchors = topDiv.find('ul.tabs a');
      panelDivs = topDiv.find('div.panel');
      lastAnchor = null;
      lastPanel = null;
      anchors.show();
      lastAnchor = anchors.filter('.on');
      lastPanel = $(lastAnchor.attr('href'));
      panelDivs.hide();
      lastPanel.show();
      return anchors.click(function(event) {
        var currentAnchor, currentPanel;
        event.preventDefault();
        currentAnchor = $(this);
        currentPanel = $(currentAnchor.attr('href'));
        lastAnchor.removeClass('on');
        currentAnchor.addClass('on');
        lastPanel.hide();
        currentPanel.show();
        lastAnchor = currentAnchor;
        return lastPanel = currentPanel;
      });
    });
  });

}).call(this);
