// Generated by CoffeeScript 1.3.3
(function() {
  var Manju, manju1, manju2, manju3, manju4;

  Manju = (function() {

    function Manju() {}

    Manju.prototype.taste = 'うまい';

    Manju.prototype.anko = '100グラム';

    Manju.prototype.color = 'white';

    return Manju;

  })();

  manju1 = new Manju;

  manju2 = new Manju;

  manju3 = new Manju;

  manju4 = new Manju;

  alert(manju1.taste);

  alert(manju2.taste);

  alert(manju3.anko);

  alert(manju4.anko);

}).call(this);
